### ISSUE TITLE
Request / This is the future of runescape SOISOISOI

### ISSUE THREAD

**Issue by Wynadorn** [techgaud/TTS#4]
Any chance it could be extended to also use clan chat?

I'd also love to see some familiar voices like Microsoft SAM or DECTalk (Moonbase Alpha / Stephen Hawking)

**Comment by cthulhuwaits** [comment]
I'm vision impaired. not super bad but enough where I get debilitating headaches looking at letters and trying to read. so you guys are really appreciated. some of the longer dialogs don't read. but yall should create a patron wither a "cheap" tear so I could support it. kina poor but wana help. thanks for all the work so far tho!! seriously. makes RuneScape easier to play.
